bibliotekafilmowa/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]


from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]


from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('movies/', views.MovieListView.as_view(), name='movies'),
    path('movie/<int:pk>', views.MovieDetailView.as_view(), name='movie-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('actors/', views.ActorListView.as_view(), name='actors'),
    path('actor/<int:pk>', views.ActorDetailView.as_view(), name='actor-detail'),
    path('genres/', views.GenreListView.as_view(), name='genres'),
    path('genre/<int:pk>', views.GenreDetailView.as_view(), name='genre-detail'),
    path('mymovies/', views.LoanedMoviesByUserListView.as_view(), name='my-borrowed'),
    path('borrowedmovies/', views.LoanedMoviesByUsers.as_view(), name='user-borrowed'),
    path('movie/<uuid:pk>/renew/', views.renew_movie_librarian, name='renew-movie-librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('movie/create/', views.MovieCreate.as_view(), name='movie-create'),
    path('movie/<int:pk>/update/', views.MovieUpdate.as_view(), name='movie-update'),
    path('movie/<int:pk>/delete/', views.MovieDelete.as_view(), name='movie-delete'),
    path('signup/', views.signup, name='signup'),
]

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from datetime import date

from django.contrib.auth.models import User

class Genre(models.Model):
   
    name = models.CharField(max_length=200, help_text='Enter a movie genre (e.g. Science Fiction)')

    def get_absolute_url(self):
     
        return reverse('genre-detail', args=[str(self.id)])

    def __str__(self):
        
        return self.name


class Movie(models.Model):
    
    title = models.CharField(max_length=200)

  
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    actor = models.ManyToManyField('Actor', help_text='Add actor to this movie')
    release = models.IntegerField('Release', help_text='Year of Movie release',null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the movie')
    imdb = models.CharField('IMDb', max_length=13, unique=True,
                             help_text='7 or 8 Character <a href="https://www.imdb.com/">IMDb number</a>')

   
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this movie')

    def __str__(self):
        
        return self.title

    def get_absolute_url(self):
        
        return reverse('movie-detail', args=[str(self.id)])
    
    def display_genre(self):
        
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'

    def display_actors(self):
     
        return ', '.join(actor.first_name +' ' +actor.last_name for actor in self.actor.all()[:3])

    display_actors.short_description = 'Actors'

class MovieInstance(models.Model):
   
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular movie across whole library')
    movie = models.ForeignKey('Movie', on_delete=models.RESTRICT, null=True)
    type = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Movie availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set movie as returned"),)
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False
    def __str__(self):
        
        return f'{self.id} ({self.movie.title})'


class Author(models.Model):

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
     
        return f'{self.first_name} {self.last_name}'


class Actor(models.Model):
 
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
      
        return reverse('actor-detail', args=[str(self.id)])

    def __str__(self):
        
        return f'{self.first_name} {self.last_name}'

catalog/forms.py
import datetime

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class RenewMovieForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
    def clean_first_name(self):
        data = self.cleaned_data['first_name']

        
        return data

    def clean_last_name(self):
        data = self.cleaned_data['last_name']

        return data

    def clean_email(self):
        data = self.cleaned_data['email']

        
        return data

catalog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Movie, Author, MovieInstance, Genre, Actor
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required
import datetime
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from catalog.models import Author
from catalog.forms import RenewMovieForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.template import RequestContext
from catalog.forms import SignUpForm

@login_required
def index(request):
    """View function for home page of site."""

    
    num_movies = Movie.objects.all().count()
    num_instances = MovieInstance.objects.all().count()

    
    num_instances_available = MovieInstance.objects.filter(status__exact='a').count()

    
    num_genres = Genre.objects.count()   
    num_authors = Author.objects.count()
    num_actors = Actor.objects.count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    context = {
        'num_movies': num_movies,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_actors' : num_actors,
        'num_genres' : num_genres,
        'num_visits': num_visits,
    }

    
    return render(request, 'index.html', context=context)

from django.views import generic

class MovieListView(LoginRequiredMixin,generic.ListView):
    model = Movie
    paginate_by = 10


class MovieDetailView(LoginRequiredMixin,generic.DetailView):
    model = Movie

    
class AuthorListView(LoginRequiredMixin,generic.ListView):
    model = Author
    paginate_by = 10


class AuthorDetailView(LoginRequiredMixin,generic.DetailView):
    model = Author

    
class ActorListView(LoginRequiredMixin,generic.ListView):
    model = Actor
    paginate_by = 10


class ActorDetailView(LoginRequiredMixin,generic.DetailView):
    model = Actor

class GenreListView(LoginRequiredMixin,generic.ListView):
    model = Genre
    paginate_by = 10


class GenreDetailView(LoginRequiredMixin,generic.DetailView):
    model = Genre

class LoanedMoviesByUserListView(LoginRequiredMixin,generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = MovieInstance
    template_name ='catalog/movieinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return MovieInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

class LoanedMoviesByUsers(PermissionRequiredMixin,generic.ListView):
    permission_required = 'catalog.can_mark_returned'
    model = MovieInstance
    template_name ='catalog/movieinstance_list_borrowed.html'
    paginate_by = 10

    def get_queryset(self):
        return MovieInstance.objects.filter(status__exact='o').order_by('due_back')


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_movie_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    movie_instance = get_object_or_404(MovieInstance, pk=pk)

    
    if request.method == 'POST':

       
        form = RenewMovieForm(request.POST)

       
        if form.is_valid():
            
            movie_instance.due_back = form.cleaned_data['renewal_date']
            movie_instance.save()

           
            return HttpResponseRedirect(reverse('all-borrowed') )

    
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewMovieForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'movie_instance': movie_instance,
    }

    return render(request, 'catalog/movie_renew_librarian.html', context)

class AuthorCreate(CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    

class AuthorUpdate(UpdateView):
    model = Author
    fields = '__all__' 

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')



class MovieCreate(CreateView):
    model = Movie
    fields = '__all__'
    

class MovieUpdate(UpdateView):
    model = Movie
    fields = '__all__' 

class MovieDelete(DeleteView):
    model = Movie
    success_url = reverse_lazy('movies')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

catalog/templates/catalog/actor_detail.html
  
{% extends "base_generic.html" %}

{% block content %}

<h1>Actor: {{ actor }} </h1>
<p>{{actor.date_of_birth}} - {% if actor.date_of_death %}{{actor.date_of_death}}{% endif %}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Movies</h4>

<dl>
{% for movie in actor.movie_set.all %}
  <dt><a href="{% url 'movie-detail' movie.pk %}">{{movie}}</a> ({{movie.movieinstance_set.all.count}})</dt>
  <dd>{{movie.summary}}</dd>
{% endfor %}
</dl>

</div>
{% endblock %}

catalog/templates/catalog/actor_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Actor List</h1>
  {% if actor_list %}
  <ul>
    {% for actor in actor_list %}
      <li>
        <a href="{{ actor.get_absolute_url }}">{{ actor.first_name }} {{actor.last_name}}</a> 
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no actors in the library.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/author_detail.html
  
{% extends "base_generic.html" %}

{% block content %}

<h1>Author: {{ author }} </h1>
<p>{{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Movies</h4>

<dl>
{% for movie in author.movie_set.all %}
  <dt><a href="{% url 'movie-detail' movie.pk %}">{{movie}}</a> ({{movie.movieinstance_set.all.count}})</dt>
  <dd>{{movie.summary}}</dd>
{% endfor %}
</dl>

</div>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author List</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{author.last_name}}</a> 
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no authors in the library.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/genre_detail.html
  
{% extends "base_generic.html" %}

{% block content %}

<h1>Genre: {{ genre }} </h1>


<div style="margin-left:20px;margin-top:20px">
<h4>Movies</h4>

<dl>
{% for movie in genre.movie_set.all %}
  <dt><a href="{% url 'movie-detail' movie.pk %}">{{movie}}</a> ({{movie.movieinstance_set.all.count}})</dt>
  <dd>{{movie.summary}}</dd>
{% endfor %}
</dl>

</div>
{% endblock %}

catalog/templates/catalog/genre_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Genre List</h1>
  {% if genre_list %}
  <ul>
    {% for genre in genre_list %}
      <li>
        <a href="{{ genre.get_absolute_url }}">{{ genre.name }} </a> 
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no genres in the library.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/movie_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ movie.title }}</h1>

  <p><strong>Author:</strong> <a href="{{ movie.author.get_absolute_url }}">{{ movie.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ movie.summary }}</p>
  <p><strong>IMDb:</strong><a href="https://www.imdb.com/title/tt{{movie.imdb}}/"> {{ movie.imdb }}</a></p>
  <p><strong>Genre:</strong> {{ movie.genre.all|join:", " }}</p>
  <p><strong>Actors:
  
  {%for actor in movie.actor.all%}
  <a href="{{ actor.get_absolute_url }}">{{actor}} |</a>
  
  {%endfor%}
  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in movie.movieinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Type:</strong> {{ copy.type }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/movie_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/movie_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Movie List</h1>
  {% if movie_list %}
  <ul>
    {% for movie in movie_list %}
      <li>
        <a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a> ({{movie.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no movies in the library.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/movie_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ movie_instance.movie.title }}</h1>
  <p>Borrower: {{ movie_instance.borrower }}</p>
  <p{% if movie_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ movie_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/movieinstance_list_borrowed.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed movies</h1>

    {% if movieinstance_list %}
    <ul>

      {% for movieinst in movieinstance_list %}
      <li class="{% if movieinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'movie-detail' movieinst.movie.pk %}">{{movieinst.movie.title}}</a> ({{ movieinst.due_back }}) ({{ movieinst.borrower }}) <a href="{% url 'renew-movie-librarian' movieinst.id %}">Renew</a>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no movies borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/movieinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed movies</h1>

    {% if movieinstance_list %}
    <ul>

      {% for movieinst in movieinstance_list %}
      <li class="{% if movieinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'movie-detail' movieinst.movie.pk %}">{{movieinst.movie.title}}</a> ({{ movieinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no movies borrowed.</p>
    {% endif %}
{% endblock %}